### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by hyperjuni**
- Removed broken and unnecessary Protectorate Janitor NPC behavior config.
- Removed redundant moan/orgasm config from the .species files.

### CODE REVIEW

**Review by ErinaSugino — CHANGES_REQUESTED** [review]
Just removing the data from the species files doesn't really solve the inherent problem.

The attempt to load and use data from the identity needs to be removed too. Otherwise at least the pitch of sounds remains fixed and uneditable, as the identity builder set default values in case none are present in the species file, and identity values take priority over config values.

The loading of moan-related values in the common identity script and the attempted usage of identity data in the actor moan plugin file need to be removed.

**Comment by hyperjuni** [comment]
I suggest making it so that the plugin config takes priority over all other values, since it's the most "visible" location for a player who wishes to adjust them, and already includes all of the sfx-related configuration.

**Comment by ErinaSugino** [comment]
> In my opinion, even if it doesn't fix underlying issues, cleanup of files is always a step in the right direction

It is, but because there is an underlying problem just removing the data that points at said underlying problem doesn't help as it just makes it more confusing at a later stage when there is random code referencing nothing. So since this is already a pull request from it's own branch, might as well fully deal with everything before merging.

**Review by ErinaSugino — APPROVED** [review]
Should have completely removed the species file values for moan and orgasm sound config. Potential backwards compatibility issue if any species support only uses the species file and not the config to define stuff - but in that case it only affects the moaning and it can easily be fixed by the user.

Can be **squash merged** after verification nothing got missed.

**Pull request merged**
